# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "httparty", "~> 0.18.1"

gem "colorize", "~> 0.8.1"

gem "smarter_csv", "~> 1.2"

gem "tty-prompt", "~> 0.22.0"

gem "dotenv-rails", "~> 2.7"

gem "dotenv", "~> 2.7"
